title:        Jonas, a Blag
tagline:      'Jonas, a Blag'
description:  'A Blag Story'
url:          http://andhyde.com
version:      1.1.1
author:
  name:       'Jonas'
  email:      'JSTrostle att Gmail dot com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
