title:        Jonas
tagline:      'Jonas, a Blag Story'
description:  'A Blag Story'
version:      1.1.1
author:
  name:       'Jonas'
  email:      'JSTrostle att Gmail dot com'
markdown:     rdiscount
permalink:    pretty
pygments:     false
paginate:     5
